image:
  file: .gitpod.dockerfile
ports:
  - port: 1313
    onOpen: ignore
tasks:
  - init: git submodule set-url themes/syna https://github.com/eclipsesource/syna && git submodule init && git submodule update && git submodule set-url themes/syna git@github.com:eclipsesource/syna.git && hugo
    command: hugo server

    
